---
- hosts: nodes
  tasks:
  - name: Run Docker Container
    become: true
    docker_container:
      name: hello_world
      image: nginxdemos/hello
      ports:
        - "80:80"
    tags:
    - create
  - name: Remove Docker Container
    become: true
    docker_container:
      name: hello_world
      image: nginxdemos/hello
      state: absent
    tags:
    - remove